### ISSUE TITLE
Resaon to not allow not impl_params and instance_norm for johnson_alahi_li_2016_transformer?

### ISSUE THREAD

**Issue by pmeier** [pmeier/pystiche_papers#107]
Is there a good reason for us to not allow `not impl_params and instance_norm` in `johnson_alahi_li_2016_transformer`

https://github.com/pmeier/pystiche_papers/blob/c0eb5bc850555df71accff4314d6b69733b7a907/pystiche_papers/johnson_alahi_li_2016/modules.py#L345-L346

I think my original motivation was to only include the combinations for which we have direct information on. If that is the only reason I'm in favor of lifting this restriction, and just inform the user about this fact.

Cc @jbueltemeier

**Comment by jbueltemeier** [comment]
I can't think of any reason why it wouldn't work either. But have you ever tried out if this combination works? If this goes through without error, I would agree with your approach of lifting this restriction and inform the user about this fact.

**Comment by pmeier** [comment]
It won't work right now without error, because we implemented it that way. The question should be

Is there a theoretical constraint that keeps us to enable this?

**Comment by jbueltemeier** [comment]
I can't think of any reason right now.
