### ISSUE TITLE
RuntimeError during texture synthesis

### ISSUE THREAD

**Issue by jbueltemeier** [pmeier/pystiche_papers#20]
An `RuntimeError` occurs when trying to synthesize a texture with a `ulyanov_et_al_2016_transformer`, i. e. when `sytlization=False` and for example `input=(256,256)`. 

```python
from pystiche.papers.ulyanov_et_al_2016.core import ulyanov_et_al_2016_texture_synthesis
from pystiche.papers.ulyanov_et_al_2016.modules import ulyanov_et_al_2016_transformer
transformer = ulyanov_et_al_2016_transformer(stylization=False).to("cuda")
ulyanov_et_al_2016_texture_synthesis((256,256), transformer, stylization=False)
```

**Comment by pmeier** [comment]
Since #129 removed the texture synthesis functionality, this error can no longer happen. As such I'm closing this.
