### ISSUE TITLE
GramOperator anomaly for ulyanov_et_al_2016

### ISSUE THREAD

**Issue by pmeier** [pmeier/pystiche_papers#219]
Since the initial PR (#17) the following two lines are included in the constructor of `pystiche.ulyanov_et_al_2016.GramOperator`:

https://github.com/pmeier/pystiche_papers/blob/9f2acb82191353c55370326a5f4a91cd7528d969/pystiche_papers/ulyanov_et_al_2016/_loss.py#L94-L95

While the latter is simply ignored throughout the operator, the former changes the computation of the representation:

https://github.com/pmeier/pystiche_papers/blob/9f2acb82191353c55370326a5f4a91cd7528d969/pystiche_papers/ulyanov_et_al_2016/_loss.py#L103-L109

Both parameters did not get a reference link in #109. @jbueltemeier could you have a look?

**Comment by jbueltemeier** [comment]
Fixed in [#221](https://github.com/pmeier/pystiche_papers/pull/221).
