### ISSUE TITLE
NST starting point for li_wand_2016

### ISSUE THREAD

**Issue by pmeier** [pmeier/pystiche_papers#227]
Right now the starting point is hard coded to

https://github.com/pmeier/pystiche_papers/blob/04e8e3598939679b9c9963a7c1a1b48899f30b97/pystiche_papers/li_wand_2016/_nst.py#L63-L65

This is wrong since the paper states

> [The input image] is initialized as random noise

The reference implementation [does **not** set a default](https://github.com/pmeier/CNNMRF/blob/fddcf4d01e2a6ce201059d8bc38597f74a09ba3f/transfer_CNNMRF_wrapper.lua#L557). For the predefined runs [the starting point is the `content_image`](https://github.com/pmeier/CNNMRF/blob/fddcf4d01e2a6ce201059d8bc38597f74a09ba3f/run_trans.lua#L66-L69) (see third parameter `'image'`).

How do we want to handle this?

1. `starting_point = "random"` or
2. `starting_point = "content" if impl_params else "random"`

Cc @jbueltemeier

**Comment by jbueltemeier** [comment]
Since there is [no default](https://github.com/pmeier/CNNMRF/blob/fddcf4d01e2a6ce201059d8bc38597f74a09ba3f/run_trans.lua#L9) for this parameter in the reference implementation and all examples are executed with "content", I would prefer the second variant.

> starting_point = "content" if impl_params else "random"

**Comment by pmeier** [comment]
The problem is that the parameters for the [four predefined runs](https://github.com/pmeier/CNNMRF/blob/fddcf4d01e2a6ce201059d8bc38597f74a09ba3f/run_trans.lua#L66-L69) differ from the [default parameters](https://github.com/pmeier/CNNMRF/blob/fddcf4d01e2a6ce201059d8bc38597f74a09ba3f/transfer_CNNMRF_wrapper.lua#L555-L576). Thus, even now, we have a discrepancy between the parameters used in the replication

https://github.com/pmeier/pystiche_papers/blob/04e8e3598939679b9c9963a7c1a1b48899f30b97/replication/li_wand_2016/main.py#L32-L34

and the default values

https://github.com/pmeier/pystiche_papers/blob/04e8e3598939679b9c9963a7c1a1b48899f30b97/pystiche_papers/li_wand_2016/_loss.py#L187-L192

I'm inclined to set `starting_point="random"` by default and simply switch this to `starting_point="content"` for the replication. Thoughts?
