### ISSUE TITLE
li_wand_2016 score_correction_factor

### ISSUE THREAD

**Issue by pmeier** [pmeier/pystiche_papers#228]
As of the initial implementation (#14) we have included a `score_correction_factor` in the style loss and regularization for `impl_params is True`. This was switched in #225 to use the `score_correction_factor` only if `impl_params is False`, since the comments indicated that it was only used in the paper.

I've reread the paper and can't find any mention of this. There is no constant factor in any equation. @jbueltemeier could you also have a look?

**Comment by jbueltemeier** [comment]
Okay, I've looked at it and I have a hunch. In the paper they talk about 

> squared Euclidean distance

, but in the implementation they use the [nn.MSECriterion](https://github.com/torch/nn/blob/master/doc/criterion.md#msecriterion) which has a `reduction=mean` by default.

Could it be that this `score_correction_factor` should compensate this additional reduction?

**Comment by pmeier** [comment]
IMO, the `reduction` has nothing to do with it. I think this was probably a copy-paste-error from either [`gatys_ecker_bethge_2016`](https://arxiv.org/pdf/1508.06576.pdf) or [`gatys_et_al_2017`](https://arxiv.org/pdf/1611.07865.pdf). You can find the score correction factor in these papers in equations (1) and (4) as well as (4).

**Comment by jbueltemeier** [comment]
Since I found no other justification yesterday, I will agree with you that this can be removed.
