### ISSUE TITLE
Double name spacing

### ISSUE THREAD

**Issue by pmeier** [pmeier/pystiche_papers#56]
Currently, every paper reference implementation is name-spaced twice. For Example:

```python
pystiche_papers.gatys_ecker_bethge_2015.gatys_ecker_bethge_nst()
```

This is very cumbersome and does not provide a lot in return. The only time I can think of where this would be helpful if one imports it at the top of a file and only uses it far away from the imports:

```python
from pystiche_papers.gatys_ecker_bethge_2015 import gatys_ecker_bethge_nst

a_lot_of_lines_since_top_of_file = True

output_image = gatys_ecker_bethge_nst()
```

---

I suggest we remove the second name-spacing, i. e. 

```python
pystiche_papers.gatys_ecker_bethge_2015.nst()
```

If we import the sub-package opposed to individual functions we also do not lose explicitness:

```python
from pystiche_papers import gatys_ecker_bethge_2015

a_lot_of_lines_since_top_of_file = True

output_image = gatys_ecker_bethge.nst()
```

Furthermore this allows us to do 

```python
from pystiche_papers import gatys_ecker_bethge_2015 as paper

paper.nst()
```
which is more concise if the context allows it.

@jbueltemeier If we want to do this, we should wait until we reach significant test coverage in order not to break anything.

**Comment by jbueltemeier** [comment]
That's a very good idea. I also find the variant without second name-spacing much more pleasant to read and as you said, the explicitness is not lost.

**Comment by pmeier** [comment]
I'll take this up when we hit significant coverage.
